### ISSUE TITLE
Charts zoom out time frame whenever app reloads

### ISSUE THREAD

**Issue by inewell** [xh/toolbox#233] opened 2019-07-26 14:19 UTC
Navigate to Toolbox -> Charts Tab. If you zoom in, then as soon as the app reloads the chart returns to the full zoomed-out time frame.

**Comment by TomTirapani** [comment] 2019-07-27 16:20
I recall solving this same issue in the context of client app recently... let me take a look on Monday and see if it can be generalised at the hoist-react level

**Comment by lbwexler** [comment] 2019-08-07 17:44
isaac -- maybe a good thing to look at this afternoon, if you have some cycles?

**Comment by peterjcoffman** [comment] 2019-11-22 16:42
There are two charts the user can zoom in on. They both display the same data. Should they use the same zoom level or should they each remember their own?

**Comment by lbwexler** [comment] 2019-11-22 19:09
Discussed with Peter.  This relates to maintaining zoom state across data
load, not page refresh.  And the chart examples can all be handled
independently.

Peter:  Note that this also is a problem for the chart in the Portfolio
App.  We may or may not want that chart to rezoom its state
when a different instrument is loaded, but we definitely do *not* want it
to re-zoom on data reload for a given instrument.

**Comment by peterjcoffman** [comment] 2019-11-25 21:42
This seems to affect all charts.

The following change in hoist-react should change the default behavior so changes to data will not re-zoom a chart:

https://github.com/xh/hoist-react/pull/1455

**Comment by lbwexler** [comment] 2019-12-02 16:34
Closing this -- the issue is being worked on in the context of hoist-react

**Closed by lbwexler** 2019-12-02 16:34 UTC
